### ISSUE TITLE
UI freeze on typing

### ISSUE THREAD

**Issue by psycha0s** [intellij-dlanguage/intellij-dlanguage#455]
I installed this plugin on Windows and configured paths to different D tools (dcd, dscanner, dfmt). Now, when I try to type in a simple "hello world" program, I get massive UI freezes after every single character.

This is the code I'm playing with:
```
import std.stdio;

void foo(int value) {
	writefln("value=%d", value);
}

void main() {
	foo(20);
}
```

Is it a known issue? Is there a workaround? Thanks!

**Comment by andre2007** [comment]
With the next version of the D plugin for IntelliJ there are at least 2 fixes which will improve the performance a lot. On Windows DCD caused a major slow down if paths to phobos and DRuntime weren't set correctly. The paths will be automatically determined correctly with next release. As workaround for now set the paths in DCD server settings args field just as paths separated by commas. Second correction is to avoid building binaries for syntax checking while you typing characters. Maybe there are even more performance related bug fixes.

**Comment by phantom-code** [comment]
I tried to set paths as you suggested but it didn't help. Autocompletion works fine for a couple of seconds and then starts to freeze again. I guess I entered wrong paths or dcd-server doesn't "understand" Windows path format. I'm gonna wait for the next release, thanks for the quick answer and help!

**Comment by SingingBush** [comment]
v1.17 is now in the [plugin repo](https://plugins.jetbrains.com/plugin/8115). You should be able to update soon

**Comment by phantom-code** [comment]
Thank you for the quick update! Sadly, it seems that the issue is still here. Autocompletion works for a few times and then it starts to freeze on typing again. For instance, using my code from the first post: if I try to add an additional argument to the function foo, it starts to freeze.

**Comment by SingingBush** [comment]
ok will reopen. Can you let us know the versions of each D tool and if they were pre-compiled or did you compile them (if you did compile them, were they compiled with ldc?).

**Comment by phantom-code** [comment]
I use dmd 2.081.1 and a pre-built binary of dcd 0.9.9, downloaded from the github page. dcd files were placed into the dmd's bin directory.
Although, dcd version is displayed as 0.9.8 in the settings dialog:
![screenshot_2](https://user-images.githubusercontent.com/8014057/42685923-0a1d77d0-869d-11e8-89b8-c9f30466e175.png)

**Comment by phantom-code** [comment]
I have this issue on two different machines. Although, I configured all tools in the same way. I tried to play with DCD alone and it seems it works just fine. I think there is something else that causes the freeze.
I'd like to investigate this issue, but I'm pretty new to IDEA plugins development. Could you please tell me what I should do to be able to build and play it myself, maybe I find something? Is having IDEA with some Java SDK installed enough?

**Comment by andre2007** [comment]
On every key press dub is executed to check the source code. The errors you see in the editor (If there is s.th. wrong) are produced by these dub calls. With the newest version there was a fix that these dub calls no longer created binary files but anyway the calls can create a high work load and at the moment there is no way to disable it. I created issue #458 for this. Do you have a powerful pc?Maybe your anti virus scanner slows down the dub calls?It tried your example and can not reproduce the issue unfortunately. To get started plugin development have a look at the end of readme.md (search for gradle).

**Comment by phantom-code** [comment]
My main PC is pretty good (7900X), it shouldn't cause this.
I just got an interesting result: I forgot about dcd-server running in the terminal and configured dcd tools in the configuration dialog. As far as I understood,  it started to use my instance of dcd-server, because I see messages in the terminal. The issue has gone. If I stop my dcd-server, the issue returns.

**Comment by andre2007** [comment]
Yes, if DCD client is defined in IntelliJ and DCD server is not available, the editor almost becomes unusable.
The question is what exactly happens.

As you said auto completion works a few times and then the freeze begins: Maybe DCD server is crashing at a specific point in time and then this will cause the UI freeze. If this is the reason, there are 2 bugs: 1 in DCD and 1 in IntelliJ: In my opinion even if the server is not available, the IntelliJ IDE should not freeze. I

**Comment by phantom-code** [comment]
Is there a way to get some log info about the DCD server status (and probably a crash)?

**Comment by andre2007** [comment]
I am not aware of any logs or  any server status

**Comment by andre2007** [comment]
While thinking about this issue, I wonder whether DCD client or DCD server is crashing. The server is started once. The client is executed every time source code code completion is triggered.

You can help me investigating the cause of this issue. Set DCD server and client in settings and when again the freeze occur please test whether you can start DCD client manually from console (terminal) and try to execute "dcd-client --query".
If you get some response like "Server is running" that means server was not crashing, but one of the client crashed,

**Comment by phantom-code** [comment]
I did what you suggested and got `Server is not running`

**Comment by andre2007** [comment]
Thanks a lot for trying out. I will try to find a solution. For your information, next plugin version will come with 2 changes regarding DCD. The special handling of dcd server flags is removed. Now the values you enter here will be passed through to DCD server executable. Second change: the sourcepaths from sdk (https://user-images.githubusercontent.com/1451047/42837986-e7321238-89ff-11e8-8ae9-7ff5f304306e.png) will be added as imports to dcd server and to D-scanner.

**Comment by pirocks** [comment]
> My main PC is pretty good (7900X)

@phantom-code Is your harddrive particularly slow/is your filesystem network mounted?

**Comment by phantom-code** [comment]
@pirocks No, I don't even have a HDD installed, only an SSD. It seems that dcd server just crashes when it's launched by the dlanguage plugin. The question is why it happens because it doesn't crash when launched manually in the terminal.

**Comment by andre2007** [comment]
I faced same issue when the import paths for DCD server were wrong. With latest IntelliJ Dlanguage plugin update released a few days ago, this should not happen anymore. If the SDK paths are right, DCD server will use these paths:

![image](https://user-images.githubusercontent.com/1451047/43797856-0d9ee65a-9a89-11e8-9be5-62a94a0d1e0a.png)

But you also wrote it works a few times and then suddenly stops. That sounds like another issue than mine.

**Comment by phantom-code** [comment]
I just updated to the latest version. Yes, the issue is still here. When autocompletion invokes for the very first time, everything freezes for a second and then the completion list appears. And it just freezes for 1-2 seconds at every next time.
![image](https://user-images.githubusercontent.com/8014057/43798618-cdf89540-9a93-11e8-8c58-2edd7eea780d.png)

**Comment by phantom-code** [comment]
I don't know the exact moment when it happens but this error message appears on the background:
![image](https://user-images.githubusercontent.com/8014057/43798988-dc70f04e-9a94-11e8-95bc-b2bd9dfec3d5.png)

**Comment by phantom-code** [comment]
It appears just after I close IDEA.

**Comment by SingingBush** [comment]
There are a few [DCD std.socket.SocketOSException issues](https://github.com/dlang-community/DCD/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+std.socket.SocketOSException) so I suspect this is a combination of the plugin doing something it shouldn't as well as DCD not handling errors well. 

I'll setup _dcd-v0.9.10-windows-x86_ and take a look.

**Comment by mleise** [comment]
It looks like I may have the same issue on Linux. IDE is responsive for a while then seconds of freezes on every key press. `dcd-client --query` shows the server is no longer running.

**Comment by andre2007** [comment]
Issue on Windows should be solved with fix in dcd client application https://github.com/dlang-community/DCD/pull/569

**Comment by andre2007** [comment]
New release
https://github.com/dlang-community/DCD/releases/tag/v0.11.0

**Comment by psycha0s** [comment]
It seems that the issue is still here. At some point dcd-server (or client) crashes and typing becomes impossible. And I get this window in the background:
![image](https://user-images.githubusercontent.com/8014057/52582501-6347a300-2e3e-11e9-8757-4143ea7a8ab0.png)

**Comment by andre2007** [comment]
I also received this dialog box but I am not sure whether this specific dialog is really thrown by DCD or by dmd/ldc/dfmrt/dscanner.

In general I deactivated automatic code completion and use it only on key press ( I think it is and + space).

**Comment by psycha0s** [comment]
I launch dcd-server in the terminal before launching IDEA manually. This way it works flawlessly.

**Comment by RUSshy** [comment]
I recently switched to vscode, and DLS plugin is just incredibly good  https://github.com/d-language-server/dls, no freeze at all

I prefer intellij so maybe you guys could use DLS instead of DCD ? there is a plugin for LSP in intellij

**Comment by andre2007** [comment]
As written on the forum(https://forum.dlang.org/post/esiptlmgczikkyxgrnhn@forum.dlang.org),  yes DLS is fantastic and you can use it in addition to the D IntelliJ plugin. The goal clearly should be to make directly use of language server protocols like DLS.

Another performance issue are the massive calls to Dub for syntax checking.
If someone has time, there should be a new checkbox in the settings for easily enable/disable it. At the moment you need to do this hack https://github.com/intellij-dlanguage/intellij-dlanguage/issues/331.

**Comment by SingingBush** [comment]
Changes for this issue have been released in 1.21 which is in the plugin repo. It would be helpful to have some feedback as to whether or not the changes have helped

**Comment by SingingBush** [comment]
problems with DCD integration should be resolved in next release. Certainly with any reasonable sized files. I suspect there may be problems with huge files (likes 1,000 lines long) but for most users the changes should resolve dcd problems.
